### ISSUE TITLE
Review Tooling used by 18F and how we can transition to alternative tools

### ISSUE THREAD

**Issue by jeromeleecms** [CMSgov/eAPD#1807]
As we prepare for procurement, we want to minimize the impact of transitioning 18F off of the project while we onboard a new vendor. We need to identify any tools used by 18F that are used under their license and identify alternatives or steps to ensure CMS has it's own license for them.

### This task is done when...
 - [ ] Team has compiled a list of tools/sites that are currently utilized on the project
 - [ ] Each tool/site has an alternative tool/site identified (if applicable)
- [ ] Any potential new tools/site are identified
- [ ] Steps have been identified to ensure no disruption in design/development of the product prior to or after a new vendor has been onboarded

**Comment by jeromeleecms** [comment]
How do we transition documents/material away from Google drive?

**Comment by jeromeleecms** [comment]
Migrating from 
- 18F Slack -> CMS Slack
- Mural 
- 18F Github -> CMS Github
- 18F CircleCI -> ??

Also link to Wiki for list we should look to update:
https://github.com/18F/cms-hitech-apd/wiki/Workflows-and-processes
