### ISSUE TITLE
Transfer cms-hitech-apd repo to CMS

### ISSUE THREAD

**Issue by mgwalker** [CMSgov/eAPD#1907]
This repo currently lives in the @18F Github org. It should be transferred to the @CMSgov org so CMS can own it. This should be completed before a vendor onboards.

### This task is done when...
- [ ] repo is transferred from @18F to @CMSgov
- [ ] eAPD product owner(s) have administrative permissions on the transferred repo, so they can add collaborators as necessary
- [ ] repo is setup with CI/CD
  - [ ] CircleCI is configured to build from the new repo
  - [ ] environment variables are setup in CircleCI
  - [ ] build scripts are updated to point to the new repo (there are only a few places that need to be updated)

**Comment by jeromeleecms** [comment]
Per the CMS folks that setup our CMSgov repo, we need to put in a JIRA ticket to kick off the process to do the migration. When we are ready to act on this, JIRA it is!

**Comment by cthulhuplus** [comment]
https://help.github.com/en/github/administering-a-repository/transferring-a-repository

If you transfer a private repository to a GitHub Free user or organization account, the repository will lose access to features like protected branches and GitHub Pages. For more information, see "GitHub's products."

When you transfer a repository, its issues, pull requests, wiki, stars, and watchers are also transferred. If the transferred repository contains webhooks, services, secrets, or deploy keys, they will remain associated after the transfer is complete. Git information about commits, including contributions, is preserved.

When you use git clone, git fetch, or git push on a transferred repository, these commands will redirect to the new repository location or URL. However, to avoid confusion, we strongly recommend updating any existing local clones to point to the new repository URL. You can do this by using git remote on the command line:

$ git remote set-url origin new_url

To transfer repositories to an organization, you must have repository creation permissions in the receiving organization. If organization owners have disabled repository creation by organization members, only organization owners can transfer repositories out of or into the organization.

Once a repository is transferred to an organization, the organization's default repository permission settings and default membership privileges will apply to the transferred repository.

**Comment by cthulhuplus** [comment]
ZenHub's "Edit Workspace" supports multiple repos. We should be able to add the CMS repo and remove the 18F repo when ready to make the switch over. All issues, assignments, and labels are tracked in GitHub, so when we do the ownership transfer of repositories those should also transfer and because we are adding to our existing. ZenHub says:

"Cross-org repository transfers are managed through GitHub using repository transfers. If you need to move a repo, you won't lose any associated ZenHub data."

https://help.zenhub.com/support/solutions/articles/43000010366-moving-a-repo-cross-organization-or-to-a-new-organization

**Comment by cthulhuplus** [comment]
Once transfered/migrated add new CMS repo to Codcov, there's just a button to add a repo. May need to create/update a Repository Upload Token. 

Note: Token not required for public repositories uploading from Travis, CircleCI or AppVeyor.

**Comment by cthulhuplus** [comment]
GitHub
Create a staging branch on CMS Repo
Copy all files and directories to staging branch of CMS Repo
Run files locally from staging branch of CMS Repo
Test staging branch of CMS Repo on your local dev environment 
Push files up to staging branch of CMS Repo

CircleCI
Navigate to CMS CircleCI
Check Workflows > My branches for presence of staging branch of CMS Repo

ZenHub
Check CMS ZenHub

Codecov 
Check CMS Codecov(?)

Slack Integration
Looks like this is handled by CircleCI

CircleCI
Merge a branch, run tests, create a preview build
