### ISSUE TITLE
Content review of Nav Bar

### ISSUE THREAD

**Issue by CSwartzHMA** [CMSgov/eAPD#2243]
Review titles and cascading to maximize navigation and readability and ensure users can quickly access all sections of the app.
This also includes 
- Looking at content of page represented
- Looking at areas where we thought there was a mismatch nav titles vs page titles
- Considering pages that are not in the nav that should be added in

Related
- See convo in #2170 about the new "State Costs Summary" table
- Change Title of section to Actual Expenditures to match content changes in #2252
- The headings in the Activity Overview section needs attention (look at nav and corresponding headers) 
- Title change on Activity Schedule Summary to "Summary Schedule by Activity" consistent with the new summary budget table language
- On Activity Schedule Summary Remove “activity milestone” to just Milestone
- Milestones should be on the nav bar, but it’s not currently. 
- In Activities section, we'd previously discussed with Activities List was better or Activities Management. Let's revisit. 

### This task is done when...
 - [x] Navigation patterns within the app using the Left Nav have been reviewed
 - [x] Recommendations for changes have been documented
 - [x] Team has reviewed recommendations and made decisions about follow up actions

**Comment by CSwartzHMA** [comment]
Consider back and next button actions.

**Comment by jjames521** [comment]
For ease of use @CSwartzHMA @beparticular I put together a nav user flow

![NavigationUserFlow.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/acf7460a-a481-4b4b-9a1f-e062e42e55c3)

**Comment by CSwartzHMA** [comment]
This is awesome! Thanks! I had started a review of the matchup of the nav bar contents vs. page contents, but hadn't thought so much about the flow of the navigation between pages. Very insightful.

**Comment by CSwartzHMA** [comment]
[Nav Bar content review.xlsx](https://github.com/18F/cms-hitech-apd/files/4737863/Nav.Bar.content.review.xlsx)
@beparticular @jjames521

**Comment by CSwartzHMA** [comment]
Updated version after initial discussion. Second round of review in process to address remaining three areas outlined in this document:  
[Nav Bar content review.xlsx](https://github.com/18F/cms-hitech-apd/files/4754258/Nav.Bar.content.review.xlsx)

**Comment by CSwartzHMA** [comment]
@beparticular Here is the updated version. Please let me know if you want to set up some time to review and who should be involved. Here is what I have done:
1 - Updated to reflect changes recently made in the app.
2 - Added info about buttons.
3 - Included (in yellow) table titles. I did not review content within the tables since that is out of scope for this issue, I believe, and most tables have already been reviewed as part of other issues.
[Nav Bar content review.xlsx](https://github.com/18F/cms-hitech-apd/files/4915266/Nav.Bar.content.review.xlsx)

**Comment by CSwartzHMA** [comment]
Team review has been completed and resulting action items have been rolled into new issues.

**Comment by beparticular** [comment]
FYI I re-opened this to create an epic, but no work needs to be done on this particular issue. (Experimenting with zenhub, pardon our progress, etc)

**Comment by beparticular** [comment]
Issues have been completed for this epic. Closing. Woo!
