### ISSUE TITLE
Design the log in process

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#2362]
After the Okta implementation #2345, the UI will need to be designed to support MFA as part of the log in process.

### This task is done when...
 - [x] Design how messaging will show in the event of errors or system down (might be separate issue)
 - [ ] Other criteria TBD after the dev ticket is being worked on
 - [x] The design is created and approved by product

**Comment by thetif** [comment]
https://app.mural.co/t/cmsmural6360/m/cmsmural6360/1597164018648/28971bd0eb6a909145b0f6f4da6853480ebab4eb

**Comment by jjames521** [comment]
@beparticular @thetif @radavis 

Log In Flow:

Includes customized components, iconography and annotation for review.

https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2020?node-id=787%3A8
