### ISSUE TITLE
Transition from CircleCI to GitHub Actions

### ISSUE THREAD

**Issue by cthulhuplus** [CMSgov/eAPD#2952]
Move workflows and jobs from CircleCI to GitHub Actions

### This task is done when...
 - [ ] Cleanup Preview Deploys is successfully running in GHA
 - [ ] Nightly Dependency Vulnerability Scan is successfully running in GHA
 - [ ] Test, Build, and Deploy is successfully running in GHA

**Comment by cthulhuplus** [comment]
1 workflow per file
CircleCI Workflows
Cleanup Preview Deploys **(Good starting Candidate)**
Nightly Vulnerability Scan **(Good starting Candidate)**
Test, Build, Deploy

Jobs
Cleanup Preview Deploys **(Good starting Candidate)**
- Cleanup Preview Deploys

Nightly Vulnerability Scan **(Good starting Candidate)**
- Backend Dependency Vulnerability Scan
- Frontend Dependency Vulnerability Scan

Test, Build, Deploy
# independent jobs
- Install Dependencies
- OWASP Zap Scan
- Validate OpenAPI
- YAML Test
# backend jobs
- Backend API Endpoint Test
- Dependency Vulnerability Scan
- Backend Lint
- Backend Unit Test
- Backend Deploy
# frontend jobs
- Dependency Vulnerability Scan
- Frontend Lint
- Frontend Test
- Frontend Build Preview
- Frontend Build Staging
- Frontend Build Production
- Frontend Deploy Staging
- Frontend Deploy Production
# jointjobs
- Preview Deploy
- Store Artifacts Staging
- Store Artifacts Production
