### ISSUE TITLE
Finalize Roles and Authentication needed before go-live

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3004]
There are a number of minor things that should be done before we go-live, mostly in regards to federal users and system admin user.

### This task is done when...
 - [ ] There is a process for importing and managing State Admin certifications (#2962)
 - [ ] There is a "state" for federal users to request (#2929)
 - [ ] There is a Federal Admin panel for approving all roles from Federal Admin down (#2811, #2812)
 - [ ] The State Admin cannot see the State Admin Dashboard if their access was revoked (#2934)
 - [ ] The issue with expired passwords and MFA users has been resolved (#2988)
 - [ ] The user can request multiple states (#2638, #2582)
 - [ ] The user can switch states (#2581)
 - [ ] The Admin role has been updated to allow Admins view only rights to all states (there should be a script to add and remove Admins) (#2964)
 - [ ] The interaction with Okta has been updated to use login instead of Okta id (#2960)

**Comment by thetif** [comment]
closing because all of the tickets are closed
