### ISSUE TITLE
Practice an emergency bug patch (and create checklist for such)

### ISSUE THREAD

**Issue by NAretakis** [CMSgov/eAPD#3050]
Per the go-live tabletop exercise, we wanted to Practice an emergency bug patch (and create checklist for such)

### This task is done when...
 - [ ] Declare change that must be made (even if it is just words on a button)
 - [ ] Do any design/content work and product approval
 - [ ] Code Fix and test it
 - [ ] Deploy to prod and verify change (and run regression checks)
 - [ ] Regression checks
 - [ ] Document process and findings (repeat if needed)

**Comment by thetif** [comment]
Performed tabletop exercise and created the following steps:

1. The On-Call DevOps team members monitor slack and email using the rotation schedule.
2. If an issue is reported, they create a ticket, rate the severity, and name a main POC.
3. The POC responds to the user that reported the issue to say that the issue is being investigated and give them the ticket number for tracking.
4. If the bug is determined to not be an emergency, it can be worked as normal, otherwise continue.
5. Create an incident report.
6. The POC coordinates the team to triage the issue. Checking the logs, checking the database, using their sys admin account.
7. Once the issue is determined, check to see if there is a workaround and confirm that it works.
8. If there is a confirmed workaround, share it with the user and include it in the ticket.
9. Conduct a meeting with the Design team, the POC, and Product (if available). Determine the best solution, whether temporary or long term, and add it to the ticket.
10. Code the solution, create the PR, put it at top of the code review pipeline, add a high priority flag, reach out in slack in the team channel to make sure it’s addressed ASAP.
11. As it moves through the columns, it should continue being added to the top of each column and pinging the team in the channel so that everyone is aware of when their help is needed.
12. Once it’s made it through Code Review, QA, and Design Review, Nick or Jerome will approve it and it can be merged into main.
  - Nick has given his approval to do an emergency merge, if Jerome and Nick are gone, as long as it has followed all of the standard processes and is sev1.
13. Once it has been merged into main, it should be tested in Staging by the POC to make sure it still functions like expected.
14. Draft an emergency release and Nick or Jerome will release it to Production.
  - Nick has given his approval to do an emergency release, if Jerome and Nick are gone and it fixes a sev1 issue.
15. Confirm that the fix works in Production, and if so, reply to the user that the issue is resolved.
16. The team should then perform a post-mortem to discuss the issue. If this was a temporary solution, spin up a new issue (referencing bug issue) for the long term fix. See if there are lessons learned from the bug. Determine any next step action items.
17. Complete the incident report and close the issue.

**Comment by thetif** [comment]
@NAretakis do we still want to perform an actual bug fix or was the theoretical one sufficient?
