### ISSUE TITLE
Get a go/no-go decision for Layer 1 Go-Live

### ISSUE THREAD

**Issue by NAretakis** [CMSgov/eAPD#3052]
Per the go-live tabletop exercise we wanted get a go-live date that all of the leads support. Because of the multitude of the go-live related issues, we need to setup a process to track the remaining go-live issues to help us inform the go-live decision making.

### This task is done when the necessary go-live issues are completed and we've set a go-live date:
 - [x] Go-Live date is set, and it is: July 12, 2021 _written in pencil_
 - [ ]  #3004 Finalize Roles and Authentication needed before go-live **EPIC**
 - [ ] #2409 Communication plan to support release planning **EPIC**
 - [ ] #2727 Changes needed before release **EPIC**

**Comment by jeromeleecms** [comment]
Closing this out as there are no more issues here... and we are live.
