### ISSUE TITLE
Create a roadmap to move towards automated testing

### ISSUE THREAD

**Issue by jeromeleecms** [CMSgov/eAPD#3084]
Before implementing automated testing for the application, we'll need to develop a roadmap to establish scale and scope for an incremental implementation. In the roadmap, we should see a high level description for the "piece" of work to be completed and an estimate level of effort to complete the work.

Going to leave this a little lite for the description, but will rely on @thetif and @eStar386 to help think through some of the specifics on how to map this out.

### This task is done when...
 - [ ] Dev Lead and QA have a roadmap to implement automated testing
 - [ ] Product has signed off on roadmap
- [ ] Issues have been created to reflect the work in the roadmap

**Comment by eStar386** [comment]
https://app.mural.co/t/cmsmural6360/m/cmsmural6360/1619794874835/87245e171dfad4934ecee8b6020251550445a4b3 - Creating an agile test plan documenting testing related activities with the related user stories.
@thetif @jeromeleecms

**Comment by thetif** [comment]
Cypress implementation has begun.
