### ISSUE TITLE
Transition APDs to MongoDB

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3100]
The APDs are currently being stored in a single BSON field in Postgres. Moving them to MongoDB would provide more flexibility for validation and interaction. See #2833 for research findings.

### This task is done when...
 - [ ] future and existing APDs are stored in MongoDB instead of Postgres
 - [ ] when the api is updated to query MongoDB instead of Postgres
 - [ ] the CI/CD is updated to include MongoDB

**Comment by jeromeleecms** [comment]
Done - thanks for Bill and Tif and team for making the dream come true!!!!!
