### ISSUE TITLE
[Design Issue] Revisit the empty state alert for sections (milestones, state staff, etc)

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#3317]
It's generally not a good pattern to use red warning alerts to indicate that a field hasn't been filled out on the first visit as no error has been made. At times we've seen in research that folks get confused about why this alert appears. In the most recent round, the user thought that they had missed an input somewhere else in the system that wasn't populating this field, rather than realizing that this field needed to be filled out on the same page as the alert. 

While most folks do figure this out, this will need to be taken into consideration when we're looking at validation and how we alert users to required fields. The current design could clash with new design decisions - see next paragraph. 

In addition, when we start doing validation at the end of an APD, we need a way to alert users that these are missing sections. Not all of these sections currently use the alert pattern or should. I'm not sure if the alert pattern is the way to go, but it could be for a section vs a field. 

Sections that have this pattern of enter a section, add information, click done to add an entry. 
- Required. Can show some kind of alert if these fields are entered. Should it be before they create an entry, or as part of the error check? 
  - At least one Primary Point of Contact (Key Personnel)
  - At least one Activity (this will not be an issue until MES Expansion, but let's go ahead and design it holistically with the rest) 
  - At least one Outcome (does not have to have metrics) 
- Has this same pattern, but is not required. This means that red alert should never show for these sections, since they not required. 
  - Milestone
  - State Staff
  - State expenses
  - Private Contractors

### This task is done when…

- [x] Consider starting a validation EPIC. 
- [ ] designs are created, taking into consideration multiple FFY, multiple entries, long entries, weird entries, and/or the export view if applicable
- [ ] 508 considerations and/or recommendations are reviewed
- [ ] designs are shared
- [ ] designs are approved by product
- [ ] if there is a long discussion, a summary of changes for dev will be added to the last comment before transfer
- [ ] a list of changes to be made if this is improving an existing feature

**Comment by beparticular** [comment]
Some experimental design views for posterity

![thiswouldprobablyworkforvalidationalert.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/6ac4d18f-cb29-4caf-bd5e-100de760973b)

![Thisseemsaloteasier now.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/0908bac1-907f-43a0-bec1-6dce4cc5d962)

**Comment by beparticular** [comment]
@thetif this is the summary we talked about. 

Remove the red alert where the option isn't needed (see original description for not required fields) 
Keep the alert where the option is required, however it's triggered by the error check. It doesn't show automatically. 
Note the line added in the designs to indicate that something should be added.

**Comment by thetif** [comment]
Created dev tickets #3491, #3493, #3494, #3495, #3496, #3497, #3498, #3499
