### ISSUE TITLE
Add e2e tests for Activities - Outcomes and milestones

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3328]
### Description and related issues - 
Working off of the APD created in #3313, write tests that fills in the Outcome and milestones fields for Activity 1 and Activity 2.

activities/04

### Test cases needed...

- [x] should be able to fill in the Outcomes and milestones section
    - [x] should handle Outcomes
        - [x] should create an Outcome and metrics
            - [x] click Add outcome
            - [x] should be able to fill in Outcome
            - [x] should be able to fill in Metric
            - [x] should be able to add another Metric and fill it out
            - [x] click Done
            - [x] verify that Outcome is the value entered above
            - [x] verify that Metrics has the two metrics entered above
        - [x] should edit Outcome and metrics
            - [x] click Add and Done
            - [x] click edit next to the new Outcome
            - [x] should be able to fill in Outcome
            - [x] should be able to fill in Metric
            - [x] should be able to add another Metric and fill it out
            - [x] click Done
            - [x] verify that Outcome is the values entered above
            - [x] verify that Metrics has the two metrics entered above
        - [x] should delete the first Metric
            - [x] click Edit next to the Outcome
            - [x] click Delete next to the first Metric
            - [x] verify that clicking Delete closes the modal and does delete the Metric
            - [x] verify that the second metric is now the first metric
        - [x] should delete the Outcome
            - [x] click Delete next to the first Outcome
            - [x] verify that clicking Delete closes the modal and does delete the Outcome
            - [x] verify that the second Outcome is now the first outcome
    - [x] should handle Milestones
        - [x] should create an Milestone
            - [x] click Add milestone
            - [x] should be able to fill in Name
            - [x] should be able to fill in Target completion date
            - [x] click Done
            - [x] verify that Milestone 1 has the values entered above for name
            - [x] verify that Milestone 1 Target completion date has the value entered above
        - [x] should edit milestone
            - [x] click Add milestone and Done
            - [x] should be able to fill in Name
            - [x] should be able to fill in Target completion date
            - [x] click Done
            - [x] verify that Milestone 2 has the values entered above for name
            - [x] verify that Milestone 2 has the Target completion date entered above
        - [x] should delete Milestone
            - [x] click Delete next to the first Milestone
            - [x] verify that clicking Delete closes the modal and does delete the milestone
            - [x] verify that the 2nd milestone has become the 1st milestone
