### ISSUE TITLE
Add e2e tests for Activities - Budget and FFP

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3333]
### Description and related issues - 
Working off of the APD created in #3313, write tests that fills in the Budget and FFP fields for Activity 1.

activities/08

### This task is done when...

- [x] should be able to verify Budget and FFP
    - [x] should display the Budget for FFY table correctly (reusable function for each year and each activity)
        - [x] verify that every state staff entered shows up and that their cost and FTE are what was entered in #3330
        - [x] verify that every other state expense shows up and that its cost is what was entered in #3330
        - [x] verify that every private contractor shows up and that its cost is what was entered in #3331
        - [x] verify that the other funding matches what was entered in #3332
        - [x] verify that Activity Total Computable Medicaid Cost is the sum of all of the values from all of the rows of the table 
    - [x] should handle Federal-State Split
        - [x] select 90-10
            - [x] verify that the Federal Share is the Activity Total * 90% and that the math is correct
            - [x] verify that the State Share is the Activity Total * 10% and that the math is correct
            - [x] verify that the Federal Share and the State Share equal the Activity Total
        - [x] select 75-25
            - [x] verify that the Federal Share is the Activity Total * 75% and that the math is correct
            - [x] verify that the State Share is the Activity Total * 25% and that the math is correct
            - [x] verify that the Federal Share and the State Share equal the Activity Total
        - [x] select 50-50
            - [x] verify that the Federal Share is the Activity Total * 50% and that the math is correct
            - [x] verify that the State Share is the Activity Total * 50% and that the math is correct
            - [x] verify that the Federal Share and the State Share equal the Activity Total
    - [x] should fill in Estimated Quarterly Expenditure (reusable for each year)
        - [x] select 75-25 from the Federal-State Split
        - [x] should handle quarters (reusable for each quarter and both cost types)
            - [x] fill in the quarter percentage
            - [x] verify that expenditure equals the Cost subtotal * the percentage entered
            - [x] verify that the total quarter cost is the sum of the two expenditures in the quarter
        - [x] should handle Subtotal (reusable by cost type)
            - [x] verify that percentage is the sum of percentages entered in the quarters
    - [x] should fill in Estimated Quarterly Expenditure for 2022 using a 50-50 split
    - [x] verify the FFY 2021-2022 Totals text using the function created in #3313
        - [x] verify that the activity title "Program Administration" is in the text
        - [x] verify that the total cost of the activity is the sum of the total costs of both FFYs in the text
        - [x] verify that other funding is the sum of the other funding in both FFYs in the text
        - [x] verify that Medicaid cost is the sum of total costs in both FFYs minus the other funding in both FFYs in the text
        - [x] verify that the split is 75/25 (FFY 2021) and 50/50 (FFY 2022) in the text
        - [x] verify that the FFYs are "FFY 2021 and FFY 2022" in the text
        - [x] verify that the federal share is the sum of the Federal share in both FFYs in the text
        - [x] verify that the Alaska share is the sum of the State share in both FFYs in the text
- [ ] fill in all the Budget and FFP fields for Activity 2 with different values from Activity 1
