### ISSUE TITLE
[Design Issue] Design a pattern for the export view for when non-required fields are not filled out 

### ISSUE THREAD

**Issue by beparticular** [CMSgov/eAPD#3345]
Some of the fields in the eAPD will not be required to be answered before submit. We have language that we use, noted in the content guide in the wiki, to note when a field isn't filled out so that it's clear to the reviewer that it wasn't a mistake or something broken in the system, but we only did this for top fields before release. Determine if we need any more language patterns or visual patterns to show when fields are not answered, when we include ALL fields in the list. 

### This task is done when…

- [ ] any acceptance criteria (not process oriented, requirements of feature)
- [x] designs are created, taking into consideration multiple FFY, multiple entries, long entries, weird entries, and/or the export view if applicable, validation considerations
- [ ] 508 considerations and/or recommendations are reviewed
- [x] designs are shared
- [ ] designs are approved by product
- [ ] if there is a long discussion, a summary of changes for dev will be added to the last comment before transfer
- [ ] a list of changes to be made if this is improving an existing feature

---

Add additional labels (design, dev, compliance, BUG, etc) and size before submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for prioritization in backlog refinement or sprint planning with Product.

**Comment by beparticular** [comment]
List of fields in export view that Tif noticed dont have a "no response provided" type message. 

Activity
- Provide a short overview of the activity:
- Statement of Alternative Considerations and Supporting Justification
- Outcomes and Metrics
- Milestones
- State staff
- Other state expenses
- Private Contractor Considerations
- Description of Cost Allocation Methodology
- Other Funding Description

**Comment by akuas** [comment]
I looked through the empty state export designs on figma, as well as the list above and came up with some copy to display. Generally, I reserved 'X not specified' for fields that I felt were not required and fields that did not require much explanation i.e. Date not specified. I used 'no x was provided' mainly for fields with long text fields and multiple fields within a section.
### **Activity**

- Use 'Activity name and corresponding fields not provided' when no information is entered for an activity.

**Provide a short overview of summary**
- No response was provided

**Statement of Alternative Considerations and Supporting Justification**
- No response was provided on the activity's alternative considerations.

**Outcomes and Metrics**
- Use 'No outcome(s) and corresponding metrics were provided." when the section is missing at least one outcome and metrics
- Use 'No metrics were included for the outcome provided.' when an outcome is included but no metrics.


**Milestones**
- Use 'No milestones were provided.' for an empty milestone section

**State Staff**
- No state staff was provided

**Other state expense**
- Other state expenses not specified

**Private Contractor**
- Private contractor(s) not specified

**Description of Cost Allocation Methodology**
- No cost allocation methodology was provided.

**Other funding description**
- No response was provided.

### Activity Schedule Summary
Activity milestones
- Use 'Activity X: Untitled | No milestones were provided' if the activity is unnamed and there are no milestones.
- Use 'Activity X: Untitled Milestones' if there are milestones but the activity is not unnamed.
- Use 'No activity milestones to display.' in the table cell if there are no milestones.
- Use 'Dates not specified' when the Activity Date Range is not available.
- Use 'Milestone name not specified.' if a milestone is unnamed. Hopefully, we would have a validation in the builder view to require the milestone name to create a milestone, so this copy might be unnecessary.

### Assurances and Compliance
Each field would have no response was provided.
i.e. 'Does this project comply with 42 CFR Part 495.348? 
No response was provided.'

**Comment by akuas** [comment]
One of the things we need to consider is for certain fields that have an 'add x' button i.e. add private contractor, add milestones, whether we should decide it should be all or nothing. Meaning, if you create a private contractor, maybe we should add a validation to complete the description of services, full contract term and hourly resource field, before one can create the private contractor/ select the 'done' button. How we structure the validation and how flexible we are to empty fields within a section, would affect the copy we need for the export.

**Comment by akuas** [comment]
Any objections or thoughts here before I add this copy to the figma designs?
@thetif @CSwartzHMA @beparticular @jeromeleecms

**Comment by beparticular** [comment]
@CSwartzHMA @jeromeleecms @akuas I created this doc for suggesting edits. Please use this and make sure your settings are on "suggesting" on the doc. 
https://docs.google.com/document/d/1FQr0kd5UREH3r-ALFtmQjLZbSA4DOUiFiUjR_UUdjDQ/edit#heading=h.fk3nvckbzun1

**Comment by beparticular** [comment]
@akuas @CSwartzHMA @jeromeleecms 
I made a small number of suggestions in the document. I like the way Akua used this content and think it matches to the larger discussion that helped us make decisions about what to include in the Content Guide to help us make faster, better and more consistent text changes.

**Comment by akuas** [comment]
I have added Jenn's suggestions to the designs. 
[Activities Empty State](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=3524%3A0)
[Activity Schedule Summary Empty State](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=4741%3A31123)
[Assurances and Compliance](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=4743%3A31165)

**Comment by CSwartzHMA** [comment]
@akuas Was the Budget and FFP field on the Activities page intentionally left blank?

Everything else looks great and I think would help for both internal reviews and for state officer reviews.

**Comment by akuas** [comment]
Good callout, I was debating putting it on this page or the separate screen i have for the budget and FFP. How do you feel about us using "No Budget and FFP to display." instead of "No Budget and FFP is provided" because the contents of the table is populated from previous work. @CSwartzHMA

**Comment by CSwartzHMA** [comment]
I feel like there is room for interpretation when we say it is not available to display. Maybe we say "Budget and FFP content not provided"?

**Comment by beparticular** [comment]
If we try to use the options in the content guide, maybe we could use
"No response was provided for the Budget and FFP."

Remember the use case, this is for the State Officer to know if information was added or not, and they wouldn't have a lot of context around what the user saw, or how the fields were populated (not in the beginning at least).

**Comment by akuas** [comment]
Okay, thats a good point. I will use the copy above. @beparticular

**Comment by beparticular** [comment]
@jeromeleecms this is ready for review

**Comment by jeromeleecms** [comment]
Just one comment, but everything else looks consistent with the style guide at the top of the Google doc.

**Comment by akuas** [comment]
@jeromeleecms Just addressed your comment and ended up keeping the three fields (state staff, other state expense, and private contractor) as  "x not specified.

**Comment by beparticular** [comment]
@thetif I believe this one is ready for dev, will double check with Jerome at design sync. 
The designs and google doc are aligned with the right content. 
Google Doc
https://docs.google.com/document/d/1FQr0kd5UREH3r-ALFtmQjLZbSA4DOUiFiUjR_UUdjDQ/edit#heading=h.fk3nvckbzun1
Designs are in comment 
https://app.zenhub.com/workspaces/cms-eapd-5a3823ad3659e94d8ee569be/issues/cmsgov/eapd/3345#issuecomment-901929423

**Comment by thetif** [comment]
dev task created #3449
