### ISSUE TITLE
[Feature] Add e2e tests for Activities - export view

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3387]
Working off the APD created in #3313, write tests to verify that all of the values added in the previous tests are being displayed properly in the export view.

activities/09

###This task is done when...

- [ ] should verify the export view
  - [ ] should verify the Executive Summary section
    - [ ] verify that there are 2 activities
    - [ ] should show values for each activity in the Executive Summary (reusable function for each activity--see #3313, using the values that were entered in #3327)
    - [ ] verify that the activity title is correct
    - [ ] verify that short overview of the activity is correct
    - [ ] verify that the start date is correct
    - [ ] verify that the end date is correct
    - [ ] verify that total cost of activity is correct
    - [ ] verify that total computable medicaid cost is correct
    - [ ] should have the correct FFY values (reusable for each FFY)
      - [ ] verify that FFY has the correct value
      - [ ] verify that Total Computable Medicaid Cost has the correct value
      - [ ] verify that the Federal share has the correct value
  - [ ] should verify the Activities section
    - [ ] verify that the activity list has 2 activities and that their titles and funding source are correct
    - [ ] should verify each Activity (reusable function for each activity--see #3313)
        - [ ] should verify Activity Overview section (using the values entered in #3327)
          - [ ] verify that the section header has the correct activity number and the correct title
          - [ ] verify that the short overview of the activity is correct
          - [ ] verify that the start date is correct
          - [ ] verify that the end date is correct
          - [ ] verify that the Activity overview is correct
          - [ ] verify that the Statement of Alternative Considerations and Supporting Justification is correct
          - [ ] verify that the Standards and Conditions, activity supports content is correct
          - [ ] verify that the Standards and Conditions, activity does not support content is correct
        - [ ] should verify Outcomes and metrics (using the values entered in #3328)
          - [ ] verify that the correct number of outcomes are present
          - [ ] should verify Outcome (reusable for each outcome)
            - [ ] verify that the outcome is correct
            - [ ] verify that it has the correct number of metrics
            - [ ] should verify Metrics (reusable for each metric)
              - [ ] verify that the metric is correct
        - [ ] should verify Milestones (using the values entered in #3328)
          - [ ] verify that the correct number of milestones are present
          - [ ] should verify Milestone (reusable for each milestone)
            - [ ] verify that the milestone is correct
            - [ ] verify that the target completion date is correct
        - [ ] should verify State Staff (using the values entered in #3330)
          - [ ] verify that the correct number of state staff are present
          - [ ] should verify State staff (reusable for each state staff)
            - [ ] verify the personnel title
            - [ ] should verify FFYs (reusable for each FFY)
              - [ ] verify that the FFY cost is correct
              - [ ] verify that the FTE is correct
              - [ ] verify that the total is correct  
        - [ ] should verify Other state expenses (using the values entered in #3330)
          - [ ] verify the correct number of Other state expenses are present
          - [ ] should verify Other state expense (reusable for each Other state expense)
            - [ ] verify the other state expense category is correct
            - [ ] should verify FFYs (reusable for each FFY)
              - [ ] verify FFY cost is correct
        - [ ] should verify Private contractor costs (using the values entered in #3331)
          - [ ] verify the correct number of Private contractor costs are present
          - [ ] should verify Private contractor cost (reusable for each Private contractor cost)
            - [ ] verify Private Contractor or Vendor Name is correct
            - [ ] verify Procurement Methodology and Description of Services is correct
            - [ ] verify that the Full contract term is correct
            - [ ] verify that the Total contract cost is correct
            - [ ] should verify if hourly (reusable for each FFY)
              - [ ] verify that the FFY Cost is correct
              - [ ] verify that the number of hours is correct
              - [ ] verify that the hourly rate is correct
            - [ ] should verify if not hourly (reusable for each FFY)
              - [ ] verify that the FFY Cost is correct
        - [ ] should verify Cost allocation (using the values entered in #3332)
          - [ ] verify that the Description of Cost Allocation Methodology is correct
        - [ ] should verify Other Funding (using the values entered in #3332)
          - [ ] should verify FFY (reusable for each FFY)
            - [ ] verify that the Other funding description is correct
            - [ ] verify that the Other funding amount is correct
        - [ ] should verify Budget and FFP (using the values entered in #3333 and #3327-#3332)
          - [ ] should display the Budget for FFY table correctly (reusable function for each FFY)
            - [ ] should verify State staff section (using values entered in #3330)
              - [ ] verify that every state staff entered is present
              - [ ] should verify state staff row (reusable for each state staff)
                - [ ] verify that the personnel title is correct
                - [ ] verify that the cost is correct
                - [ ] verify that the FTE is correct
                - [ ] verify that the total is cost X FTE
            - [ ] should verify Other state expenses (using values entered in #3330)
              - [ ] verify that every Other state expense entered is present
              - [ ] should verify other state staff row (reusable for each other state expenses)
                - [ ] verify that the other state expense category is correct
                - [ ] verify that cost is correct
            - [ ] should verify Private Contractor (using values entered in #3331)
              - [ ] verify that every Private contractor entered is present
              - [ ] should verify Private contractor (reusable for each private contractor)
                - [ ] verify that the Private Contractor or Vender Name is correct
                - [ ] should display hourly contractor
                  - [ ] verify that the hourly rate is correct
                  - [ ] verify that the hours are correct
                  - [ ] verify that the total is hourly rate x hour
                - [ ] should display non-hourly contractor
                  - [ ] verify that the cost is correct
            - [ ] should verify Other funding amounts 
              - [ ] should calculate other funding percentages
                - [ ] calculate **state staff total** = sum of state staff costs (no including other funding amount or state staff subtotal)
                - [ ] calculate **other state expenses total** = sum of other state expenses (no including other funding amount or other state expenses subtotal)
                - [ ] calculate **private contractor total** = sum of private contractor costs (no including other funding amount or private contractor subtotal)
                - [ ] calculate **activity total cost** =  sum of **state staff total** + **other state expenses total** + **private contractor total**
                - [ ] calculate **state staff other funding percentage** = **state staff total**/**activity total cost**
                - [ ] calculate **other state expense other funding percentage** = **other state expenses total**/**activity total cost**
                - [ ] calculate **private contractor other funding percentage** = **private contractor total**/**activity total cost**
              - [ ] should verify Other funding amount (reusable for each section)
                - [ ] verify that Other funding amount = section subtotal x section percentage
              - [ ] should verify Subtotal (reusable for each section)
                - [ ] verify that subtotal equals = section subtotal - Other funding amount
            - [ ] verify that Activity Total Computable Medicaid Cost is the sum of all of the subtotals from all of the sections above
            - [ ] verify that Activity Total Cost is equal to the activity total cost calculated above (sum of **state staff total** + **other state expenses total** + **private contractor total**)
            - [ ] verify that other funding is correct
            - [ ] verify that Federal Share amount = Total Computable Medicaid Costs * federal split entered in #3333
            - [ ] verify that State Share amount = Total Computable Medicaid Costs * state split entered in #3333
          - [ ] should display the Estimated Quarterly Expenditure table correctly (reusable function for each FFY)
            - [ ] calculate in-house costs = (state staff subtotal + other state expenses subtotal) * federal share
            - [ ] calculate contractor costs = private contractor subtotal * federal share
            - [ ] should verify cost row (reusable for in-house costs and contractor costs)
              - [ ] should verify each quarter
                - [ ] verify that the percentage is what was entered
                - [ ] verify that the quarter cost is the total costs * percentage
              - [ ] should verify Subtotal
                - [ ] verify that the total percentage is the sum off all of the quarter percentages
                - [ ] verify that the total cost is the sum of all of the quarter costs and is equal to the appropriate cost calculated above (either in-house costs or contractor costs)
            - [ ] should verify Total Enhanced FFP
              - [ ] should verify each quarter
                - [ ] verify that Total Enhanced FFP quarter total is the sum of both quarter totals
              - [ ] should verify Subtotal
                - [ ] verify that Total Enhanced FFP Subtotal is the sum of both subtotals
        - [ ] verify the FFY Totals text (using function created in #3313 and the values entered in #3326-#3333)
          - [ ] verify that the activity title is the value entered in #3326
          - [ ] verify that the total cost is equal to the sum of all of the subtotals (sum of **state staff subtotal** + **other state expenses subtotal** + **private contractor subtotal**) for each FFY
          - [ ] verify that other funding is the sum of all of the other fundings for each FFY
          - [ ] verify that total computable Medicaid cost is the sum of all of the Total Computable Medicaid Cost for each FFY
          - [ ] verify that the funding split is what was entered in #3333, if the funding split is the same for all FFYs it should look like 90/10 (FFY 2021 and FFY 2022) and if the funding split is different in each FFY it should look something like 90/10 (FFY 2021) and 75/25 (FFY 2022)
          - [ ] verify that federal share is the sum of all of the federal shares for each FFY
          - [ ] verify that state share is the sum of all of the state shares for each FFY
          - [ ] verify that the state is correct
