### ISSUE TITLE
Add e2e test for checking the Activity Schedule Summary for a filled out APD

### ISSUE THREAD

**Issue by mirano-darren** [CMSgov/eAPD#3436]
### Description and related issues -
Using the filled out APD created in #3326 - #3333, write a test that checks the values on the Activity Schedule Summary page.

### Test cases needed...

- [ ] should have correct values in the 'Schedule Summary by Activity' section.
    - [ ] verify the first activity listed is 'Program Administration' 
        - [ ] verify the 'Activity Date Range' matches was was entered in #3327
    - [ ] verify the second activity listed is what was entered in #3326
        - [ ] verify the 'Activity Date Range' matches was was entered in #3327
- [ ] should have correct values in the 'Milestone Tables by Activity' section.
    - [ ] verify the milestone names and date ranges match what was entered in #3328 (Reminder: The first milestone for Activity 1 was deleted per #3328)
