### ISSUE TITLE
[Feature] Update Milestone

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3496]
**Description and related issues -**

If there are no milestones, display this message above the Add milestone button

![Screen Shot 2021-09-27 at 3.10.54 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/b068f9df-e559-4014-9c91-c8cc6cc20fef)

Remove the alert message, Milestones will not be required.

----

Add in-line validation to Milestone form. The validation should appear after the user hits the Add (previously Done) button. If there are validation errors, the errors should display, nothing should be saved, and it should stay on the form until the errors are fixed.
![Screen Shot 2021-09-27 at 3.13.20 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/17eaf749-4dff-4ea7-ac44-1d3335027d10)

----

Update the Milestones view
![Screen Shot 2021-09-27 at 3.12.32 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/66319260-9ffa-40ae-be1e-8cd1ef8d0161)

### This task is done when…
- [x] add message above Add milestone button
- [x] remove alert message
- [x] add in-line validation
- [x] update to match Figma
