### ISSUE TITLE
Explore a "slim" MMIS IAPD implementation

### ISSUE THREAD

**Issue by jeromeleecms** [CMSgov/eAPD#3539]
What does it look like to submit an MMIS IAPD in the system? What changes need to occur to allow for a MMIS IAPD to be submitted to CMS?

Per Design Sync Convo 10/26

The flows that will need to be created are: 
- [ ] Create New APD > Modal - Choose HITECH or MMIS 
- [ ] Any pages/fields related to Activity 1 Program Admin being removed (#2518, #3381, #2985)

Fields that will need to be removed are: 
- [ ] HIE/HIT intros on APD overview 
- [ ] The default Program Admin Activity 1 (#2518); alternative to where Key Personnel costs are added needs to be evaluated - *updated*
- [ ] Extra budget tables (incentive payments, HIE/HIT, etc)
- [ ] Remove "Administrative Operations" from the dropdown in the non personnel state costs  - *updated*

Additional Considerations: 
- [ ] FFP Rates will need to be configured to indicate DDI or M&O when selecting from the dropdown (example:  90/10 DDI, 75/25 DDI, 50/50 DDI, 75/25 M&O, 50/50 M&O) OR have a way for the state to indicates the type of cost (DDI/M&O) in a separate dropdown when completing this section. Either way, needs to tie to a MBES line number. *updated* (#2303 ?)
- [ ] Standards and Conditions (Aka Conditions for enhanced funding) may be elevated from the activities in the project level right before the activities section - *updated* (#3170)
- [ ] Jerome will review help text for regs/compliance accuracy, including help text
- [ ] Adding a link to the outcomes repository in help text + change examples for outcomes and metrics *updated* (#2732 ?) 
- [ ] A content review will need to be done following Jerome's review for UI accuracy
- [ ] MMIS submit email needs to be included in the app
- [ ] Would need to review to see if anything in help text means adding any other fields or functionality 
- [ ] Cost Allocation and Other Funding will have differences (tbd)
- [ ] Work some of the help text from the prototype we tested on MES Expansion into the existing designs/fields on HITECH and MMIS 
- [ ] A slim version of MDBT transferable into the excel sheet must exist (Could we attached MBES line items to it)
- [ ] Quarterly expenditures can be removed *updated*
- [ ] Potential updates to the export view - *updated*

Dev considerations: 
- Dev is updated FE code to make it a little easier to understand, simplifying might make it easier to hide and show things based on APD type. 
- How to update math module for missing costs from HIT/HIE sections - *updated*
- How to apply MBES line items to budgets - *updated*

Research Considerations: 
How would we want to roll it out, potentially with beta testing in January? (#3552)

### This task is done when...

- [ ] Reviewed the existing app to see what an "MMIS implementation" for an IAPD would take
- [ ] Create tickets, as appropriate

**Comment by NAretakis** [comment]
@aricka-lewis let's do a 20 min zoom to make sure we have all the parts of this issue represented in the bite-sized issues. Then we can close this out.

**Comment by aricka-lewis** [comment]
This info is covered in corresponding issues in the MMIS Expansion epic. Closing this one!
