### ISSUE TITLE
Lockdown and Submit workflow

### ISSUE THREAD

**Issue by aricka-lewis** [CMSgov/eAPD#3653]
Based on criteria laid out in #3507 for the lock and submit feature:
Issue to be broken into smaller issues TBD

After an admin check is complete, a user should be able to lock the APD so that no other changes can be made. 

Considerations:
- This can only happen when there are no validation errors
- Where the ability to "lock" an APD shows up
- Include a way for an APD to be unlocked by state admins
- Consider removing submit button
- Prompt user that APD cannot be unlocked unless you have permission
- Provide two options upon export: export as draft OR export and lock 
- How we will provide the ability to lock based on permission (role-based?)

A very high-level take on the steps to finalizing and locking an APD:

- Create APD (draft)
- Draft is exported (#3651)
- Internal review of APD (0.1, 0.2 versions with "draft" tag)
- Admin Check performed
- Final APD is exported (version with “final” tag #3652)
- APD is finalized and locked (read only view #3654)

### This task is done when...

- [x]  designs are created, taking into consideration validation, multiple FFY, multiple entries, long entries, weird entries, and/or the export view if applicable
- [x] 508 considerations and/or recommendations are reviewed
- [x] designs are shared
- [ ] designs are approved by product
- [ ] if there is a long discussion, a summary of changes for dev will be added to the last comment before transfer
- [ ] a list of changes to be made if this is improving an existing feature

**Comment by aricka-lewis** [comment]
![Screen Shot 2021-12-28 at 10.57.00 AM.png](https://images.zenhubusercontent.com/6193eb5d55886d5a53ec4aac/ada9a268-4f3e-4a68-a118-307f61f7b862)

Lockdown and submit workflow in [UX working mural board](https://app.mural.co/t/cmsmural6360/m/cmsmural6360/1611780005309/48a85b47f678d3fd5858070e25da7025d2da0a09?sender=ucee7a982497c1a5f017c0984)

**Comment by aricka-lewis** [comment]
Next steps for this will be to review the workflow in the design sync on 01/13 so that it can be broken into smaller, workable issues.

**Comment by aricka-lewis** [comment]
@NAretakis Will you review this workflow for lockdown and submit? Happy to meet to walkthrough it if needed.

**Comment by NAretakis** [comment]
this flow looks good to me. My only question is, would a state-user be able to informally run the admin check in some way? I think that having the ability to run the admin check, even for informal internal reviews, might be valuable. 

So, the flow is good, except I am just worried about the "Perform admin check" step being a sort of gatekeeper for the subsequent steps in the flow.

**Comment by aricka-lewis** [comment]
@NAretakis update on the admin check question (definitely a longer winded answer than I'm sure you were looking for, ha!)

@akuas  and I met to talk through this workflow in detail. I'm documenting my notes here and will update this ticket accordingly.

In an internal review, reviewers check to make sure an APD is "administratively complete." This is not the same thing as an "administrative check" though the admin check could be considered part of an internal review. Agnostic of internal review, the admin check can be run at any time.

Once an admin check is run and no errors are found, an APD can be exported as a finalized and locked version (wording/language to be updated in a separate issue). 

An APD that **has not** gone through an admin check will always be exported as a **draft**. Once an APD **has** gone through an an admin check and no errors are found, it can either be exported as a **draft OR as a finalized and locked version** (depending on who has the ability to do so).

A user should be given the above option once they begin an export.

**Comment by aricka-lewis** [comment]
Updated workflow

![Screen Shot 2022-01-11 at 11.21.51 AM.png](https://images.zenhubusercontent.com/6193eb5d55886d5a53ec4aac/7e7f001e-fcd6-4e60-8d0b-54bc2790bba4)

**Comment by akuas** [comment]
@aricka-lewis thanks for adding the notes!

**Comment by NAretakis** [comment]
@aricka-lewis revised flow looks good to me, and the difference between internal review and admin check now makes sense in my head, thank you.

**Comment by akuas** [comment]
@aricka-lewis I'm now thinking since this is an epic, shouldn't this be done when every ticket within it is done?

**Comment by aricka-lewis** [comment]
Ah, true. I went on a mini-closing rampage! @akuas

**Comment by jeromeleecms** [comment]
Also -- let's just make sure that everything scoped in this Epic really needs to be part of it. For example, 3750 feels like it's creeping into implementation and less planning. Let's talk about this one during refinement.
