### ISSUE TITLE
[Epic] Restructure Front-end

### ISSUE THREAD

**Issue by thetif** [CMSgov/eAPD#3769]
The front-end components are a little jumbled and hard to find. We want to restructure the files so that they reflect the application a little more and they are a little easier to find.

the overall structure will be changed to be more like:
```
src
├── components # components used in multiple places
├── containers # central containers
├── layout # elements that are always part of the view
    ├── header
    ├── nav
    ├── footer
├── pages # trying to match these agains the routes
    ├── login
    ├── admin
        ├── state-admin
        ├── fed-admin
    ├── dashboard
        ├── state-dashboard
        ├── fed-dashboard
    ├── apd
        ├── apd-overview
        ├── state-profile rename folder and route to key-state-personnel
        ├── previous-activities
        ├── activities
            ├── activities-dashboard
            ├── overview
            ├── oms
            ├── state-costs
            ├── contractor-costs
            ├── cost-allocation
            ├── ffp
        ├── schedule-summary
        ├── proposed-budget
        ├── executive-summary
        ├── export
├── redux # moving all redux code to be located in one folder
    ├── actions
    ├── reducers
    ├── selectors # moving the selectors to their own folder
├── routes # moving routing containers to a separate folder
  ```

### This task is done when...

- [ ] components are better organized inside folders that match their routes
- [ ] components are renamed where necessary to better reflect what they are
- [ ] there are storybooks for all common components and at least every page level component

**Comment by thetif** [comment]
All completed
